    - name: Add Repo Key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927
      tags: install

    - name: Add Mongo Repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        filename: mongodb-org-3.2.list
      tags: install

    - name: Update system
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        force_apt_get: yes
      tags: install

    - name: Install MongoDB
      apt:
        name: mongodb-org
        force_apt_get: yes
      tags: install

    - name: Enable MongoDB service
      service:
        name: mongod
        enabled: yes
      tags: install